name: Astro CI/CD

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Astro
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 

  send_notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event.action == 'opened' || github.event.action == 'closed' 
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "PR Realizada com Sucesso! > ${{ github.event.action }}: ${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}"
