name: Astro CI/CD

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
 # Atualizado para a versão mais recente
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Atualizado para a versão 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build Astro
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3 # Verifique se há uma versão mais recente disponível
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 
